"""s

Revision ID: fc232f0672de
Revises: 
Create Date: 2025-04-22 21:07:06.435607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc232f0672de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('b_effect', sa.Float(), nullable=False),
    sa.Column('g_effect', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_choices_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=False),
    sa.Column('current_b', sa.Float(), nullable=False),
    sa.Column('current_g', sa.Float(), nullable=False),
    sa.Column('current_S', sa.Float(), nullable=False),
    sa.Column('current_I', sa.Float(), nullable=False),
    sa.Column('current_R', sa.Float(), nullable=False),
    sa.Column('days_passed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_simulations_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulationchoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.Column('timetaken', sa.Integer(), nullable=True),
    sa.Column('before_I', sa.Float(), nullable=True),
    sa.Column('before_S', sa.Float(), nullable=True),
    sa.Column('after_I', sa.Float(), nullable=True),
    sa.Column('after_S', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], name=op.f('fk_simulationchoices_choice_id_choices')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_simulationchoices_scenario_id_scenarios')),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_simulationchoices_simulation_id_simulations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulationresults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('final_S', sa.Float(), nullable=True),
    sa.Column('final_I', sa.Float(), nullable=True),
    sa.Column('final_R', sa.Float(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('endreason', sa.String(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_simulationresults_simulation_id_simulations')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulationresults')
    op.drop_table('simulationchoices')
    op.drop_table('simulations')
    op.drop_table('choices')
    op.drop_table('users')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
